// Generated by scripts/fetch-exact-artwork.py. Do not hand-edit.

import exactAirpodsPro1Case from '../assets/device-artwork/exact/airpods-pro-1-case.webp';
import exactAirpodsPro1Pair from '../assets/device-artwork/exact/airpods-pro-1-pair.webp';
import exactAirpodsPro1Single from '../assets/device-artwork/exact/airpods-pro-1-single.webp';
import exactBeatsStudioBudsPlusPair from '../assets/device-artwork/exact/beats-studio-buds-plus-pair.webp';
import exactGalaxyBudsPair from '../assets/device-artwork/exact/galaxy-buds-pair.webp';
import exactGalaxyBudsLivePair from '../assets/device-artwork/exact/galaxy-buds-live-pair.webp';
import exactHuaweiFreebuds6Pair from '../assets/device-artwork/exact/huawei-freebuds-6-pair.webp';
import exactJblFreePair from '../assets/device-artwork/exact/jbl-free-pair.webp';
import exactNothingEar1Case from '../assets/device-artwork/exact/nothing-ear-1-case.webp';
import exactNothingEar1Single from '../assets/device-artwork/exact/nothing-ear-1-single.webp';
import exactPixelBudsProCase from '../assets/device-artwork/exact/pixel-buds-pro-case.webp';
import exactSonyWf1000xm4Pair from '../assets/device-artwork/exact/sony-wf-1000xm4-pair.webp';
import exactSoundcoreSportX20Pair from '../assets/device-artwork/exact/soundcore-sport-x20-pair.webp';
import exactXiaomiBuds5Case from '../assets/device-artwork/exact/xiaomi-buds-5-case.webp';
import exactXiaomiBuds5Pair from '../assets/device-artwork/exact/xiaomi-buds-5-pair.webp';

export interface ExactArtworkAsset {
  src: string;
  mirrorSafe: boolean;
}

export interface ExactArtworkAssetSet {
  single?: ExactArtworkAsset;
  pair?: ExactArtworkAsset;
  case?: ExactArtworkAsset;
}

export type ExactArtworkAssetMap = Record<string, ExactArtworkAssetSet>;

export const exactArtworkAssets: ExactArtworkAssetMap = {
  'airpods-pro-1': {
    case: { src: exactAirpodsPro1Case, mirrorSafe: false },
    pair: { src: exactAirpodsPro1Pair, mirrorSafe: false },
    single: { src: exactAirpodsPro1Single, mirrorSafe: true },
  },
  'beats-studio-buds-plus': {
    pair: { src: exactBeatsStudioBudsPlusPair, mirrorSafe: false },
  },
  'galaxy-buds': {
    pair: { src: exactGalaxyBudsPair, mirrorSafe: false },
  },
  'galaxy-buds-live': {
    pair: { src: exactGalaxyBudsLivePair, mirrorSafe: false },
  },
  'huawei-freebuds-6': {
    pair: { src: exactHuaweiFreebuds6Pair, mirrorSafe: false },
  },
  'jbl-free': {
    pair: { src: exactJblFreePair, mirrorSafe: false },
  },
  'nothing-ear-1': {
    case: { src: exactNothingEar1Case, mirrorSafe: false },
    single: { src: exactNothingEar1Single, mirrorSafe: true },
  },
  'pixel-buds-pro': {
    case: { src: exactPixelBudsProCase, mirrorSafe: false },
  },
  'sony-wf-1000xm4': {
    pair: { src: exactSonyWf1000xm4Pair, mirrorSafe: false },
  },
  'soundcore-sport-x20': {
    pair: { src: exactSoundcoreSportX20Pair, mirrorSafe: false },
  },
  'xiaomi-buds-5': {
    case: { src: exactXiaomiBuds5Case, mirrorSafe: false },
    pair: { src: exactXiaomiBuds5Pair, mirrorSafe: false },
  },
};
