[package]
name = "bluetooth-windows"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
airbattery-service = { path = "../airbattery-service", version = "=0.1.0-alpha.1" }
device-protocols = { path = "../device-protocols", version = "=0.1.0-alpha.1" }
diagnostics = { path = "../diagnostics", version = "=0.1.0-alpha.1" }
futures.workspace = true
protocol-airpods = { path = "../protocol-airpods", version = "=0.1.0-alpha.1" }
shared-models = { path = "../shared-models", version = "=0.1.0-alpha.1" }
thiserror.workspace = true
time.workspace = true
tokio.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "=0.62.2", features = [
  "Devices_Bluetooth",
  "Devices_Bluetooth_Advertisement",
  "Devices_Bluetooth_GenericAttributeProfile",
  "Devices_Enumeration",
  "Devices_Radios",
  "Foundation",
  "Foundation_Collections",
  "Storage_Streams",
] }
