[package]
name = "airbattery-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
airbattery-core = { path = "../airbattery-core", version = "=0.1.0-alpha.1" }
device-protocols = { path = "../device-protocols", version = "=0.1.0-alpha.1" }
shared-models = { path = "../shared-models", version = "=0.1.0-alpha.1" }
time.workspace = true
thiserror.workspace = true

[dev-dependencies]
async-trait.workspace = true
tokio.workspace = true
