[package]
name = "airbattery-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
bluetooth-linux = { path = "../bluetooth-linux", version = "=0.1.0-alpha.1" }
clap.workspace = true
diagnostics = { path = "../diagnostics", version = "=0.1.0-alpha.1" }
hex.workspace = true
protocol-airpods = { path = "../protocol-airpods", version = "=0.1.0-alpha.1" }
serde_json.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
